#!/usr/bin/env bash

# shellcheck disable=2086

set -e
set -x

# IMG_NAME="moz_telegraf"
IMG_NAME="moz_telegraf_gcp"
IMG_VERSION="0.1.0"


# docker run -it "$IMG_NAME"
# docker run -it "$IMG_NAME" /bin/bash

# avoid quotes if $1 is undefined
docker run --init \
  -p 9273:9273 \
  -e TELEGRAF_CONFIG="$TELEGRAF_CONFIG" \
  -it "$IMG_NAME:$IMG_VERSION" \
  $1