#!/usr/bin/env bash

set -e
set -x

# IMG_NAME="moz_telegraf"
IMG_NAME="moz_telegraf_gcp_android"
IMG_VERSION="0.1.0"

# normal
docker build . -f "./Dockerfile" -t "$IMG_NAME:$IMG_VERSION"
#
# if above isn't pulling in the latest github changes:
# docker build . -f "./Dockerfile" -t "$IMG_NAME:$IMG_VERSION" --no-cache
